var st = "\"I am a student here we are using or we can say that learning to quateion\"";


var ts = "\' I am Student Here we are Using \'";
console.log(st);
console.log(ts);
let s = "con";
let t = "cat";
let v = "e";
let m = "nate";
console.log(s + t + v + m);
console.log(typeof 4);
console.log(typeof 'Seklf');
console.log(typeof 'd');
var d;
d = 9.9;
console.log(typeof d);
console.log(typeof 'd');
console.log(-(9 + 4));
console.log(-(9 - 5));
console.log(4 > 2);
console.log("aardvark" > "Zoroaster");
console.log(8 * null);
console.log("5" - 1);
console.log("5" + 1);
console.log("5" + "1");
console.log("5" - "1");
console.log(null == undefined);
console.log(null == 0);
console.log(null == 0);
console.log(null != 0);
console.log(0 == false);
console.log("" == false);
1;
!false;
4;
6;
//prompt("Enter password");
let mood = "Light";
console.log(mood);
mood = "Dark";
console.log(mood);
console.log(0);
console.log(2);
console.log(4);
console.log(6);
console.log(8);
console.log(10);
console.log(12);